---
pipeline:
  workspace:
    path: github.com/rancher/dapper
  build:
    image: rancher/dapper:1.10.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - CROSS=1 dapper -d
